# Generated by Django 2.2 on 2021-09-19 10:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Anahtar Kelime')),
            ],
            options={
                'verbose_name': 'EN Anahtar Kelime',
                'verbose_name_plural': 'EN Anahtar Kelimeler',
            },
        ),
        migrations.CreateModel(
            name='ReferenceTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Şirket Adı:')),
                ('image', models.ImageField(upload_to='references', verbose_name='Resim:')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link:')),
            ],
            options={
                'verbose_name': 'Referans',
                'verbose_name_plural': 'Referanslarımız',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_layer1', models.CharField(max_length=100, verbose_name='Slider Başlığı (1.Satır):')),
                ('title_layer2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slider Başlığı (2.Satır):')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Slider İçeriği:')),
                ('button_url', models.CharField(max_length=300, verbose_name='SSlider Yönlendirme Linki:')),
                ('sliderimage', models.ImageField(upload_to='slider', verbose_name='Slider Görseli:')),
            ],
            options={
                'verbose_name': 'TR Slider İçeriği',
                'verbose_name_plural': 'TR Slider İçerikleri',
            },
        ),
        migrations.CreateModel(
            name='HomeSeoTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('meta_keywords', models.ManyToManyField(to='seotr.KeywordsTr', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'TR SEO Anasayfa',
                'verbose_name_plural': 'TR SEO Anasayfa',
            },
        ),
        migrations.CreateModel(
            name='ApplicationTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('banner_title', models.CharField(max_length=200, verbose_name='Banner Başlık:')),
                ('banner_image', models.ImageField(upload_to='applications/banner', verbose_name='Banner Resmi:')),
                ('meta_keywords', models.ManyToManyField(to='seotr.KeywordsTr', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'TR Uygulamalar SEO',
                'verbose_name_plural': 'TR Uygulamalar SEO',
            },
        ),
        migrations.CreateModel(
            name='ApplicationCategoryTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık:')),
                ('banner_title', models.CharField(max_length=200, verbose_name='Banner Başlık:')),
                ('banner_image', models.ImageField(upload_to='applications/category', verbose_name='Banner Resim:')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL Uzantısı:')),
                ('meta_keywords', models.ManyToManyField(to='seotr.KeywordsTr', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'TR Uygulama Kategori',
                'verbose_name_plural': 'TR Uygulama Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='AboutTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('banner', models.CharField(max_length=200, verbose_name='Banner Başlık:')),
                ('banner_image', models.ImageField(upload_to='about', verbose_name='Banner Görseli:')),
                ('title1', models.CharField(max_length=200, verbose_name='Açıklama Başlığı')),
                ('body1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama İçeriği:')),
                ('image1', models.ImageField(upload_to='about', verbose_name='Açıklama Görseli:')),
                ('title2', models.CharField(max_length=200, verbose_name='Alt Açıklama Başlığı:')),
                ('body2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Alt Açıklama İçeriği:')),
                ('image2', models.ImageField(upload_to='about', verbose_name='Alt Açıklama Görseli:')),
                ('meta_keywords', models.ManyToManyField(to='seotr.KeywordsTr', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'TR Hakkımızda Sayfası',
                'verbose_name_plural': 'TR Hakkımızda Sayfası',
            },
        ),
    ]
