# Generated by Django 2.2 on 2021-09-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seotr', '0002_applicationsubcategorytr'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsubcategorytr',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/pdf', verbose_name='Broşür Dosyası'),
        ),
        migrations.AlterField(
            model_name='applicationsubcategorytr',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applications/items/', verbose_name='İçerik Resmi:'),
        ),
    ]
