# Generated by Django 2.2 on 2021-09-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seotr', '0005_blogcategorytr_blogcontenttr_blogpageseotr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcontenttr',
            options={'verbose_name': 'TR Blog İçerik', 'verbose_name_plural': 'TR Blog İçerikleri'},
        ),
    ]
