# Generated by Django 2.2 on 2021-09-19 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seotr', '0006_auto_20210919_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontenttr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Eklenme Zamanı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcontenttr',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı'),
        ),
    ]
