# Generated by Django 2.2 on 2021-09-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seotr', '0009_kvkkaydınlatmametnitr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordstr',
            options={'verbose_name': 'TR Anahtar Kelime', 'verbose_name_plural': 'TR Anahtar Kelimeler'},
        ),
    ]
