# Generated by Django 2.2 on 2021-09-19 10:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaKeywordEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Anahtar Kelime')),
            ],
            options={
                'verbose_name': 'EN Anahtar Kelime',
                'verbose_name_plural': 'EN Anahtar Kelimeler',
            },
        ),
        migrations.CreateModel(
            name='SliderEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_layer1', models.CharField(max_length=100, verbose_name='Slider Başlığı (1.Satır):')),
                ('title_layer2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slider Başlığı (2.Satır):')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Slider İçeriği:')),
                ('button_url', models.CharField(max_length=300, verbose_name='SSlider Yönlendirme Linki:')),
                ('sliderimage', models.ImageField(upload_to='slider', verbose_name='Slider Görseli:')),
            ],
            options={
                'verbose_name': 'EN Slider İçeriği',
                'verbose_name_plural': 'EN Slider İçerikleri',
            },
        ),
        migrations.CreateModel(
            name='HomeSeoEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('meta_keywords', models.ManyToManyField(to='seoen.MetaKeywordEn', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'EN SEO Anasayfa',
                'verbose_name_plural': 'EN SEO Anasayfa',
            },
        ),
        migrations.CreateModel(
            name='AboutEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('banner', models.CharField(max_length=200, verbose_name='Banner Başlık:')),
                ('banner_image', models.ImageField(upload_to='about', verbose_name='Banner Görseli:')),
                ('title1', models.CharField(max_length=200, verbose_name='Açıklama Başlığı')),
                ('body1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama İçeriği:')),
                ('image1', models.ImageField(upload_to='about', verbose_name='Açıklama Görseli:')),
                ('title2', models.CharField(max_length=200, verbose_name='Alt Açıklama Başlığı:')),
                ('body2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Alt Açıklama İçeriği:')),
                ('image2', models.ImageField(upload_to='about', verbose_name='Alt Açıklama Görseli:')),
                ('meta_keywords', models.ManyToManyField(to='seoen.MetaKeywordEn', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'EN Hakkımızda Sayfası',
                'verbose_name_plural': 'EN Hakkımızda Sayfası',
            },
        ),
    ]
