# Generated by Django 2.2 on 2021-09-19 11:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seoen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCategoryEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık:')),
                ('banner_title', models.CharField(max_length=200, verbose_name='Banner Başlık:')),
                ('banner_image', models.ImageField(upload_to='applications/category', verbose_name='Banner Resim:')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL Uzantısı:')),
                ('meta_keywords', models.ManyToManyField(to='seoen.MetaKeywordEn', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'TR Uygulama Kategori',
                'verbose_name_plural': 'TR Uygulama Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSubCategoryEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('banner_title', models.CharField(max_length=200, verbose_name='Banner Başlık:')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık:')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama:')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='applications/items/', verbose_name='Kapak Resmi:')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL Uzantısı:')),
                ('image', models.ImageField(blank=True, null=True, upload_to='applications/items/', verbose_name='Kapak Resmi:')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seoen.ApplicationCategoryEn')),
                ('meta_keywords', models.ManyToManyField(to='seoen.MetaKeywordEn', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'EN Uygulama Alt Kategorisi',
                'verbose_name_plural': 'EN Uygulama Alt Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='ApplicationEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('banner_title', models.CharField(max_length=200, verbose_name='Banner Başlık:')),
                ('banner_image', models.ImageField(upload_to='applications/banner', verbose_name='Banner Resmi:')),
                ('meta_keywords', models.ManyToManyField(to='seoen.MetaKeywordEn', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'TR Uygulamalar SEO',
                'verbose_name_plural': 'TR Uygulamalar SEO',
            },
        ),
    ]
