# Generated by Django 2.2 on 2021-09-19 12:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoen', '0003_auto_20210919_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('banner_title', models.CharField(max_length=200, verbose_name='Banner Başlık:')),
                ('title', models.CharField(max_length=200, verbose_name='İçerik Başlığı')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Kalite İçeriği:')),
                ('banner_image', models.ImageField(upload_to='quality', verbose_name='Banner Resmi:')),
                ('image', models.ImageField(upload_to='quality', verbose_name='İçerik Resmi:')),
                ('meta_keywords', models.ManyToManyField(to='seoen.MetaKeywordEn', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'EN Kalite Sayfası',
                'verbose_name_plural': 'EN Kalite Sayfası',
            },
        ),
    ]
