# Generated by Django 2.2 on 2021-09-19 12:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seoen', '0004_qualityen'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('title', models.CharField(max_length=200, verbose_name='Blog Kategori:')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL Uzantısı:')),
                ('banner_title', models.CharField(max_length=200, verbose_name='Banner Başlık:')),
                ('meta_keywords', models.ManyToManyField(to='seoen.MetaKeywordEn', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'EN Blog Kategori',
                'verbose_name_plural': 'EN Blog Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='BlogPageSeoEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('banner_title', models.CharField(max_length=200, verbose_name='Banner Başlık:')),
                ('banner_image', models.ImageField(upload_to='blog', verbose_name='Banner Görseli:')),
                ('meta_keywords', models.ManyToManyField(to='seoen.MetaKeywordEn', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'EN Blog Sayfası SEO',
                'verbose_name_plural': 'EN Blog Sayfası SEO',
            },
        ),
        migrations.CreateModel(
            name='BlogContentEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO Başlığı:')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Açıklaması:')),
                ('banner_title', models.CharField(max_length=200, verbose_name='Banner Başlık:')),
                ('title', models.CharField(max_length=200, verbose_name='İçerik Başlık:')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL Uzantısı:')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Blog İçeriği:')),
                ('image', models.ImageField(upload_to='blog', verbose_name='Blog Görseli:')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seoen.BlogCategoryEn', verbose_name='Blog Kategori')),
                ('meta_keywords', models.ManyToManyField(to='seoen.MetaKeywordEn', verbose_name='Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'TR Blog İçerik',
                'verbose_name_plural': 'TR Blog İçerikleri',
            },
        ),
    ]
