# Generated by Django 2.2 on 2021-09-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seoen', '0008_kvkkaydınlatmametnien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationcategoryen',
            options={'verbose_name': 'EN Uygulama Kategori', 'verbose_name_plural': 'EN Uygulama Kategorileri'},
        ),
        migrations.AlterModelOptions(
            name='applicationen',
            options={'verbose_name': 'EN Uygulamalar SEO', 'verbose_name_plural': 'EN Uygulamalar SEO'},
        ),
        migrations.AlterModelOptions(
            name='blogcontenten',
            options={'verbose_name': 'EN Blog İçerik', 'verbose_name_plural': 'EN Blog İçerikleri'},
        ),
    ]
